server {
    listen 80;
    server_name 8.147.57.104;

    root /var/www/reminder-frontend;
    index index.html;

    client_max_body_size 20m;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
