"""update document table

Revision ID: d44ce83b855d
Revises: 
Create Date: 2026-04-03 18:47:22.591790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44ce83b855d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False, comment='会话ID'),
    sa.Column('knowledge_base_id', sa.String(length=64), nullable=True, comment='所属知识库ID'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_knowledge_base_id', 'chat_sessions', ['knowledge_base_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False, comment='文档ID'),
    sa.Column('knowledge_base_id', sa.String(length=64), nullable=True, comment='所属知识库ID'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小，单位字节'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='文档状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_knowledge_base_id', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('task_records',
    sa.Column('id', sa.String(length=64), nullable=False, comment='任务ID'),
    sa.Column('task_type', sa.String(length=100), nullable=False, comment='任务类型'),
    sa.Column('target_id', sa.String(length=64), nullable=False, comment='目标对象ID'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='任务状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_records_status', 'task_records', ['status'], unique=False)
    op.create_index('idx_task_records_target_id', 'task_records', ['target_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=64), nullable=False, comment='Chunk ID'),
    sa.Column('document_id', sa.String(length=64), nullable=False, comment='所属文档ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Chunk 顺序号'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本块内容'),
    sa.Column('page_no', sa.Integer(), nullable=True, comment='页码'),
    sa.Column('start_offset', sa.Integer(), nullable=True, comment='起始偏移量'),
    sa.Column('end_offset', sa.Integer(), nullable=True, comment='结束偏移量'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_task_records_target_id', table_name='task_records')
    op.drop_index('idx_task_records_status', table_name='task_records')
    op.drop_table('task_records')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_knowledge_base_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_chat_sessions_knowledge_base_id', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
